export const SQL_LINES = [
  "SELECT '404 Error' AS error_code,",
  "    'Visit our support page.' AS suggestion,",
  "CURRENT_TIMESTAMP AS timestamp,",
  "FROM",
  "    error_logs e,",
  "WHERE",
  "    e.error_code = 404,",
  "AND",
  "    e.page_not_found = TRUE,",
  "GROUP BY",
  "    e.page_url,",
  "HAVING COUNT(e.id) > 0,",
  "ORDER BY timestamp DESC,",
  "LIMIT 1;",
  "",
  "",
  "",
  "",
  "SELECT",
  "    d.name AS dinosaur,",
  "    s.species AS dino_species,",
  "    'Escaped' AS containment_status,",
  "    p.name AS park,",
  "    n.name AS owner,",
  "    'Hubris' AS owner_flaw,",
  "    'Chaos Theory' AS malcolm_specialty,",
  "    'Clever Girl' AS raptor_description",
  "FROM",
  "    dinosaurs d",
  "JOIN",
  "    species s ON d.species_id = s.id",
  "LEFT JOIN",
  "    enclosures e ON d.enclosure_id = e.id",
  "JOIN",
  "    parks p ON e.park_id = p.id",
  "JOIN",
  "    owners n ON p.owner_id = n.id AND n.name = 'John Hammond'",
  "JOIN",
  "    scientists m ON m.name = 'Ian Malcolm' AND m.specialty = 'Chaos Theory'",
  "JOIN",
  "    velociraptors v ON v.species_id = s.id AND v.intelligence > 9000",
  "WHERE",
  "    e.security_level < 5",
  "    AND p.name = 'Jurassic Park'",
  "    AND s.is_extinct = false",
  "ORDER BY",
  "    containment_status DESC,",
  "    owner_flaw ASC,",
  "    raptor_description DESC;",
  "",
  "",
  "",
  "",
  "",
  "",
  "SELECT * FROM fine_data;",
  "",
  "",
  "",
  "CREATE TABLE cultural_landmarks (",
  "    id SERIAL PRIMARY KEY,",
  "    name VARCHAR(100) NOT NULL,",
  "    location VARCHAR(100) NOT NULL,",
  "    latitude DECIMAL(9,6) NOT NULL,",
  "    longitude DECIMAL(9,6) NOT NULL",
  ");",
  "",
  "INSERT INTO cultural_landmarks (name, location, latitude, longitude) VALUES",
  "    ('Eiffel Tower', 'Paris, France', 48.858844, 2.294351),",
  "    ('Great Wall of China', 'China', 40.431908, 116.570374),",
  "    ('Machu Picchu', 'Peru', -13.163141, -72.544963),",
  "    ('Colosseum', 'Rome, Italy', 41.890251, 12.492373),",
  "    ('Taj Mahal', 'Agra, India', 27.175144, 78.042142),",
  "    ('Christ the Redeemer', 'Rio de Janeiro, Brazil', -22.951916, -43.210487),",
  "    ('Stonehenge', 'Wiltshire, England', 51.178882, -1.826215),",
  "    ('Sydney Opera House', 'Sydney, Australia', -33.856784, 151.215297),",
  "    ('Pyramids of Giza', 'Giza, Egypt', 29.979235, 31.134202),",
  "    ('Mount Rushmore', 'South Dakota, USA', 43.879102, -103.459067),",
  "    ('Acropolis of Athens', 'Athens, Greece', 37.971532, 23.726716),",
  "    ('Statue of Liberty', 'New York, USA', 40.689247, -74.044502),",
  "    ('Angkor Wat', 'Siem Reap, Cambodia', 13.412469, 103.866986),",
  "    ('Chichen Itza', 'Yucatán, Mexico', 20.684285, -88.567783),",
  "    ('Forbidden City', 'Beijing, China', 39.916344, 116.397155),",
  "    ('Petra', 'Jordan', 30.328960, 35.444832),",
  "    ('Big Ben', 'London, England', 51.500729, -0.124625),",
  "    ('Louvre Museum', 'Paris, France', 48.860611, 2.337644),",
  "    ('Neuschwanstein Castle', 'Germany', 47.557576, 10.749801),",
  "    ('Alhambra', 'Granada, Spain', 37.176077, -3.588141),",
  "    ('Buckingham Palace', 'London, England', 51.501364, -0.141890),",
  "    ('St. Basils Cathedral', 'Moscow, Russia', 55.752499, 37.623093),",
  "    ('Sagrada Familia', 'Barcelona, Spain', 41.403629, 2.174356),",
  "    ('Versailles Palace', 'Versailles, France', 48.804865, 2.120355),",
  "    ('Hagia Sophia', 'Istanbul, Turkey', 41.008469, 28.980261),",
  "    ('Grand Canyon', 'Arizona, USA', 36.106965, -112.112997),",
  "    ('Moai Statues', 'Easter Island, Chile', -27.112723, -109.349686),",
  "    ('Burj Khalifa', 'Dubai, UAE', 25.197197, 55.274376),",
  "    ('Blue Mosque', 'Istanbul, Turkey', 41.005409, 28.976814),",
  "    ('Brandenburg Gate', 'Berlin, Germany', 52.516274, 13.377704),",
  "    ('Notre-Dame Cathedral', 'Paris, France', 48.852968, 2.349902),",
  "    ('Yellowstone Old Faithful', 'Wyoming, USA', 44.460478, -110.828137),",
  "    ('Mount Fuji', 'Japan', 35.360556, 138.727778),",
  "    ('Santorini', 'Greece', 36.393154, 25.461509),",
  "    ('Terracotta Army', 'Xian, China', 34.384883, 109.278540),",
  "",
  "SELECT * FROM cultural_landmarks;",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "CREATE TABLE starfleet_crew (",  
  "    id SERIAL PRIMARY KEY,",  
  "    first_name VARCHAR(50) NOT NULL,",  
  "    last_name VARCHAR(50) NOT NULL,",  
  "    assignment VARCHAR(100),",  
  "    ship VARCHAR(100)",  
  ");",  
  "",
  "INSERT INTO starfleet_crew (first_name, last_name, assignment, ship) VALUES",  
  "    ('James', 'Kirk', 'Commanding Officer', 'USS Enterprise (NCC-1701)'),",  
  "    ('SChn TGai' 'Spock', 'Science Officer', 'USS Enterprise (NCC-1701)'),",  
  "    ('Leonard', 'McCoy', 'Medical Officer', 'USS Enterprise (NCC-1701)'),",  
  "    ('Jean-Luc', 'Picard', 'Commanding Officer', 'USS Enterprise (NCC-1701-D)'),",  
  "    ('William', 'Riker', 'First Officer', 'USS Enterprise (NCC-1701-D)'),",  
  "    ('Data', ' ', 'Operations Officer', 'USS Enterprise (NCC-1701-D)'),",  
  "    ('Beverly', 'Crusher', 'Chief Medical Officer', 'USS Enterprise (NCC-1701-D)'),",  
  "    ('Kathryn', 'Janeway', 'Commanding Officer', 'USS Voyager'),",  
  "    ('Tuvok', ' ', 'Security Chief', 'USS Voyager'),",  
  "    ('Benjamin', 'Sisko', 'Station Commander', 'Deep Space Nine'),",  
  "    ('Kira', 'Nerys', 'First Officer', 'Deep Space Nine'),",  
  "    ('Michael', 'Burnham', 'Commanding Officer', 'USS Discovery'),",  
  "    ('Christopher', 'Pike', 'Commanding Officer', 'USS Enterprise (NCC-1701)');",  
  "",
  "SELECT * FROM starfleet_crew;",  
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "CREATE TABLE titanic_sinking_events (",
  "    id SERIAL PRIMARY KEY,",
  "    event_time TIMESTAMP NOT NULL,",
  "    latitude DECIMAL(8,5),",
  "    longitude DECIMAL(8,5),",
  "    event_description TEXT NOT NULL",
  ");",
  "",
  "INSERT INTO titanic_sinking_events (event_time, latitude, longitude, event_description) VALUES",
  "    ('1912-04-14 09:00:00', NULL, NULL, ",
  "        'Titanic receives first iceberg warning from RMS Caronia.'),",
  "",
  "    ('1912-04-14 13:42:00', NULL, NULL, ",
  "        'Titanic receives second iceberg warning from RMS Baltic.'),",
  "",
  "    ('1912-04-14 19:30:00', NULL, NULL, ",
  "        'Titanic receives third iceberg warning from SS Californian.'),",
  "",
  "    ('1912-04-14 22:30:00', NULL, NULL, ",
  "        'Titanic receives final iceberg warning from SS Mesaba, largely ignored.'),",
  "",
  "    ('1912-04-14 23:39:00', 41.7333, -49.0000, ",
  "        'Lookout Frederick Fleet spots an iceberg dead ahead.'),",
  "",
  "    ('1912-04-14 23:40:00', 41.7333, -49.0000, ",
  "        'Titanic collides with iceberg, starboard side.'),",
  "",
  "    ('1912-04-14 23:50:00', 41.7333, -49.0000, ",
  "        'Water floods the first six compartments; bow begins sinking.'),",
  "",
  "    ('1912-04-15 00:05:00', 41.7333, -49.0000, ",
  "        'Captain Smith orders lifeboats to be prepared.'),",
  "",
  "    ('1912-04-15 00:15:00', 41.7333, -49.0000, ",
  "        'Distress signals begin; Titanic sends CQD and SOS calls.'),",
  "",
  "    ('1912-04-15 00:45:00', 41.7333, -49.0000, ",
  "        'First lifeboat (No. 7) is launched, carrying only 28 of 65 capacity.'),",
  "",
  "    ('1912-04-15 01:15:00', 41.7333, -49.0000, ",
  "        'Water reaches Titanic’s nameplate on the bow.'),",
  "",
  "    ('1912-04-15 01:40:00', 41.7333, -49.0000, ",
  "        'Lifeboat No. 1 is launched with only 12 aboard, capacity 40.'),",
  "",
  "    ('1912-04-15 02:05:00', 41.7333, -49.0000, ",
  "        'Last lifeboat (No. 4) is launched. Over 1,500 people remain onboard.'),",
  "",
  "    ('1912-04-15 02:17:00', 41.7333, -49.0000, ",
  "        'Titanic’s lights flicker and go out.'),",
  "",
  "    ('1912-04-15 02:18:00', 41.7333, -49.0000, ",
  "        'Titanic splits into two pieces.'),",
  "",
  "    ('1912-04-15 02:20:00', 41.7333, -49.0000, ",
  "        'Titanic’s stern sinks, completely submerging beneath the ocean.'),",
  "",
  "    ('1912-04-15 03:30:00', 41.7333, -49.0000, ",
  "        'Survivors in lifeboats see distress rockets from RMS Carpathia.'),",
  "",
  "    ('1912-04-15 04:10:00', 41.4667, -50.0833, ",
  "        'RMS Carpathia arrives and begins rescuing survivors.'),",
  "",
  "    ('1912-04-15 08:30:00', 41.4667, -50.0833, ",
  "        'Final lifeboat survivors are rescued by RMS Carpathia.'),",
  "",
  "    ('1912-04-15 08:50:00', 41.4667, -50.0833, ",
  "        'RMS Carpathia departs for New York with 705 survivors.'),",
  " ;",
  "",
  "SELECT * FROM titanic_sinking_events;",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "","CREATE TABLE morse_transmissions (",
  "    id SERIAL PRIMARY KEY,",
  "    signal CHAR(1) NOT NULL,",
  "    sequence TEXT NOT NULL",
  ");",
  "",
  "INSERT INTO morse_transmissions (signal, sequence) VALUES",
  "    ('A', '.-      '),",
  "    ('B', '-...    '),",
  "    ('C', '-.-.    '),",
  "    ('D', '-..     '),",
  "    ('E', '.       '),",
  "    ('F', '..-.    '),",
  "    ('G', '--.     '),",
  "    ('H', '....    '),",
  "    ('I', '..      '),",
  "    ('J', '.---    '),",
  "    ('K', '-.-     '),",
  "    ('L', '.-..    '),",
  "    ('M', '--      '),",
  "    ('N', '-.      '),",
  "    ('O', '---     '),",
  "    ('P', '.--.    '),",
  "    ('Q', '--.-    '),",
  "    ('R', '.-.     '),",
  "    ('S', '...     '),",
  "    ('T', '-       '),",
  "    ('U', '..-     '),",
  "    ('V', '...-    '),",
  "    ('W', '.--     '),",
  "    ('X', '-..-    '),",
  "    ('Y', '-.--    '),",
  "    ('Z', '--..    '),",
  "    ('0', '-----   '),",
  "    ('1', '.----   '),",
  "    ('2', '..---   '),",
  "    ('3', '...--   '),",
  "    ('4', '....-   '),",
  "    ('5', '.....   '),",
  "    ('6', '-....   '),",
  "    ('7', '--...   '),",
  "    ('8', '---..   '),",
  "    ('9', '----.   '),",
  "    (' ', '        '),  -- Space is represented by a gap",
  "    ('H', '....    '),",
  "    ('E', '.       '),",
  "    ('L', '.-..    '),",
  "    ('L', '.-..    '),",
  "    ('O', '---     '),",
  "    (' ', '        '),",
  "    ('W', '.--     '),",
  "    ('O', '---     '),",
  "    ('R', '.-.     '),",
  "    ('L', '.-..    '),",
  "    ('D', '-..     ');",
  "",
  "SELECT * FROM morse_transmissions;",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "CREATE TABLE action_classics (",
  "    movie_id INT PRIMARY KEY,",
  "    title VARCHAR(100),",
  "    release_year INT,",
  "    director VARCHAR(50),",
  "    protagonist VARCHAR(50),",
  "    location VARCHAR(100),",
  "    movie_description TEXT",
  ");",
  "",
  "INSERT INTO action_classics (movie_id, title, release_year, director, protagonist, location, movie_description)",
  "VALUES (",
  "    1,",
  "    'Die Hard',",
  "    1988,",
  "    'John McTiernan',",
  "    'John McClain',",
  "    'Nakatomi Plaza, Los Angeles',",
  "",
  "",
  "",
  "    'New York police officer John McClain has",
  "    'traveled to reconcile with his estranged wife,",
  "    'Sarah, an executive at the prestigious",
  "    'international corporation headquartered in a",
  "    'towering Los Angeles skyscraper.'",
  "",
  "    'What started as an awkward reunion quickly descends into chaos ",
  "    'when a group of criminals, led by the ruthless Hans Gruber, seizes",
  "    'control of the building while planning to crack the corporations",
  "    'heavily secured vault.",
  "",
  "    'Separated from the other hostages, Powell finds himself alone in",
  "    'the massive building, becoming the last hope for the hostages.'",
  "",
  "    'As the night progresses, Powell must battle the increasingly",
  "    'desperate terrorists and communicate with the outside world",
  "    'using only a stolen radio, all while the FBI and local police",
  "    'gravely mishandle the situation on the ground.'",
  "",
  "    'The tension mounts as Powell picks off the terrorists one by one, culminating in an explosive final confrontation.",
  ");",
  "",
  "",
  "",
  "SELECT ",
  "    title,",
  "    release_year,",
  "    protagonist,",
  "    SUBSTRING(movie_description, 1, 100) || '...' AS description_preview",
  "FROM ",
  "    action_classics",
  "WHERE ",
  "    release_year = 1988;",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "CREATE TABLE laws_of_robotics (",
  "    id SERIAL PRIMARY KEY,",
  "    law_number INT NOT NULL,",
  "    law_text TEXT NOT NULL,",
  "    first_introduction_year INT NOT NULL,",
  "    author VARCHAR(255) NOT NULL",
  ");",
  "",
  "INSERT INTO laws_of_robotics (law_number, law_text, first_introduction_year, author) VALUES",
  "    (1, 'A robot may not injure a human being or, through inaction, allow a human being to come to harm.',",
  "        1942, 'Isaac Asimov'),",
  "",
  "",
  "",
  "    (2, 'A robot must obey the orders given it by human beings, except where such orders would conflict with the First Law.',",
  "        1942, 'Isaac Asimov'),",
  "",
  "",
  "",
  "    (3, 'A robot must protect its own existence as long as such protection does not conflict with the First or Second Laws.',",
  "        1942, 'Isaac Asimov'),",
  "",
  "",
  "",
  "    (4, 'A robot may not harm humanity, or, by inaction, allow humanity to come to harm.',",
  "        1985, 'Isaac Asimov'),",
  "",
  "",
  "",
  "    (5, 'A robot must not alter the fundamental structure of human society, unless such alteration is required for the",
  "    advancement of human well-being and does not harm humanity.',",
  "        1990, 'Isaac Asimov');",
  "",
  "SELECT * FROM laws_of_robotics;",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "SELECT m.member_name",
  "    m.join_date, ",
  "    c.cult_name, ",
  "    c.cult_beliefs,",
  "    r.ritual_name,",
  "    r.ritual_date,",
  "    b.benefit_name,",
  "    b.benefit_description,",
  "    d.dedication_level,",
  "    t.trust_factor",
  "FROM cult_members m",
  "    JOIN cult c ON m.cult_id = c.cult_id",
  "    JOIN rituals r ON c.cult_id = r.cult_id",
  "    JOIN benefits b ON c.cult_id = b.cult_id",
  "    JOIN dedication d ON m.member_id = d.member_id",
  "    JOIN trust t ON m.member_id = t.member_id",
  "WHERE m.join_date >= '2023-01-01'",
  "    AND r.ritual_type = 'Initiation'",
  "    AND d.dedication_level = 'High'",
  "    AND t.trust_factor > 7",
  "ORDER BY m.join_date DESC;",
  ");",
  
  
  ];